import type { ProceduralWorldResult } from './procedural-world-engine'

export interface AuditPenalty { id:string; label:string; points:number; critical?:boolean }
export interface QualityAudit { score:number; grade:'rejected'|'needs-improvement'|'professional'|'masterpiece'; ready:boolean; criticalFailure:boolean; categories:{semantic:number;beauty:number;readability:number;motion:number;identity:number;platform:number}; penalties:AuditPenalty[]; warnings:string[] }
function grade(score:number):QualityAudit['grade']{return score>=94?'masterpiece':score>=88?'professional':score>=82?'needs-improvement':'rejected'}
export function qualityScore(categories:QualityAudit['categories'],penalties:AuditPenalty[]=[]):QualityAudit {const raw=categories.semantic+categories.beauty+categories.readability+categories.motion+categories.identity+categories.platform; const criticalFailure=penalties.some((p)=>p.critical); const score=Math.max(0,Math.min(100,Math.round(raw-penalties.reduce((n,p)=>n+p.points,0)))); return {score,grade:grade(score),ready:score>=82&&!criticalFailure,criticalFailure,categories,penalties,warnings:penalties.map((p)=>p.label)} }
export function WorldAudit(result:ProceduralWorldResult):QualityAudit {const p:AuditPenalty[]=[]; if(result.compatibilityWarnings.length)p.push(...result.compatibilityWarnings.map((label,i)=>({id:`compat-${i}`,label,points:3}))); if(result.layoutGenome.split('|').length<4)p.push({id:'layout-flat',label:'العالم يعتمد على تبديل سطحي ولا يملك Genome تكوين كافياً.',points:20,critical:true}); if(result.world.palette.background===result.world.palette.ink)p.push({id:'contrast',label:'تباين النص والخلفية منهار.',points:30,critical:true}); const semantic=Math.min(25,18+Math.round(result.semantic.confidence*7)); const beauty=20; const readability=result.axes.density==='controlled-maximal'&&result.semantic.density==='dense'?15:20; const motion=result.semanticVerb===result.axes.motion?15:13; return qualityScore({semantic,beauty,readability,motion,identity:10,platform:10},p)}
export function MotionAudit(input:{semantic:boolean;loopSafe:boolean;meaningful:boolean;fps:number;durationValid:boolean;singleFrame?:boolean;excessGlow?:boolean;textRotation?:boolean}):QualityAudit {const p:AuditPenalty[]=[]; if(!input.semantic||!input.meaningful)p.push({id:'meaningless-motion',label:'حركة بلا معنى دلالي.',points:20,critical:true}); if(!input.loopSafe)p.push({id:'loop-seam',label:'أول وآخر Frame غير متوافقين.',points:12}); if(input.fps<30)p.push({id:'fps',label:'معدل الإطارات أقل من 30fps.',points:8}); if(!input.durationValid)p.push({id:'duration',label:'مدة الفيديو غير صحيحة.',points:25,critical:true}); if(input.singleFrame)p.push({id:'single-frame',label:'ملف الفيديو يحتوي Frame واحداً أو مدة وهمية.',points:35,critical:true}); if(input.excessGlow)p.push({id:'glow',label:'Glow مفرط.',points:8}); if(input.textRotation)p.push({id:'rotation',label:'دوران نص مقروء يضر العربية.',points:20,critical:true}); return qualityScore({semantic:input.semantic?25:8,beauty:18,readability:20,motion:input.meaningful?15:4,identity:10,platform:10},p)}
export function ReelAudit(input:{seconds:number;sceneCount:number;hookSeconds:number;duplicate:boolean;clipped:boolean;genericOpening:boolean;genericCta:boolean;safeZone:boolean}):QualityAudit {const p:AuditPenalty[]=[]; if(input.seconds<18||input.seconds>30)p.push({id:'duration',label:'مدة الريل خارج 18–30 ثانية.',points:20,critical:true}); if(input.sceneCount<5||input.sceneCount>8)p.push({id:'scenes',label:'عدد المشاهد خارج 5–8.',points:12,critical:true}); if(input.hookSeconds>1.5)p.push({id:'hook',label:'الافتتاح يتجاوز 1.5 ثانية.',points:10}); if(input.duplicate)p.push({id:'duplicate',label:'تكرار جمل داخل الريل.',points:20,critical:true}); if(input.clipped)p.push({id:'clip',label:'قص نص أو خروج عن Safe Zone.',points:30,critical:true}); if(input.genericOpening)p.push({id:'opening',label:'افتتاحية عامة لا تنطق موضوع المادة.',points:12}); if(input.genericCta)p.push({id:'cta',label:'CTA عام أو مكرر.',points:8}); if(!input.safeZone)p.push({id:'safe-zone',label:'نص مهم داخل منطقة أزرار المنصة.',points:25,critical:true}); return qualityScore({semantic:25,beauty:18,readability:input.clipped?5:20,motion:14,identity:10,platform:input.safeZone?10:2},p)}
