import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { motion, useReducedMotion } from "framer-motion";
import { EASE, FadeUp, Page, PageHead } from "../components/ui";
import { Newsletter } from "../components/extras";
import { useSeo } from "../components/seo";
import { Link } from "react-router-dom";
import { useExtras, useCmsContent } from "../lib/content";
import { loadArticleBodies } from "../lib/article-bodies";
import { pickEchoes, type VoiceEcho } from "../lib/voice-echoes";
import { Pagination, usePagedList } from "../components/Pagination";
import { buildArchiveDialogues } from "../lib/archive-dialogue";

type LiveInboxItem = {
  id: string;
  title?: string;
  note?: string;
  url?: string;
  message?: string;
  reply?: string;
  tone?: string;
  autoGenerated?: boolean;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type LiveFaq = {
  id: string;
  q?: string;
  a?: string;
  question?: string;
  answer?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type LiveTestimonial = {
  id: string;
  quote?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type WeeklyQuestion = {
  id: string;
  ar?: string;
  arNote?: string;
  take?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

const testimonialPulse = Math.floor(Date.now() / (3 * 86_400_000));
const rotateTestimonials = <T,>(arr: T[]): T[] =>
  arr.length
    ? [
        ...arr.slice(testimonialPulse % arr.length),
        ...arr.slice(0, testimonialPulse % arr.length),
      ]
    : arr;
const isPublished = (item: { status?: string; published?: boolean }) =>
  item.published !== false &&
  item.status !== "draft" &&
  item.status !== "hidden";
const clean = (value = "") => value.replace(/\s+/g, " ").trim();
const createdMillis = (value?: { seconds?: number }) =>
  Number(value?.seconds || 0) * 1000;

export default function Inbox() {
  useSeo({
    title: "رسائل على الهامش",
    path: "/inbox",
    description:
      "رسائل وأسئلة تتولد تلقائياً من الأرشيف المنشور وتصل إلى الصفحة من النظام الحي.",
  });
  const reduce = useReducedMotion();
  const liveInbox = useExtras<LiveInboxItem>("site_inbox", { realtime: true });
  const liveFaqs = useExtras<LiveFaq>("site_faqs", { realtime: true });
  const liveQuestions = useExtras<WeeklyQuestion>("site_questions", {
    realtime: true,
  });
  const liveTestimonials = useExtras<LiveTestimonial>("site_testimonials", {
    realtime: true,
  });

  /* مصدر الرسائل الوحيد هو المجموعة الحية التي يملؤها المجدول الآلي.
     لا بديل ثابتاً ولا روابط يدوية ولا أرقام مخبوزة داخل الصفحة. */
  const liveLetters = liveInbox
    .filter(isPublished)
    .filter((item) => Boolean(item.message) || item.autoGenerated === true)
    .map((item) => ({
      id: item.id,
      message: clean(
        item.message || [item.title, item.note].filter(Boolean).join(" — "),
      ),
      reply: clean(item.reply),
      tone: clean(item.tone),
    }))
    .filter((item) => item.message);

  const letters = liveLetters
    .filter((item) => item.message)
    .filter(
      (item, index, all) =>
        all.findIndex((candidate) => candidate.message === item.message) ===
        index,
    );

  const featuredLetter = letters[0];
  const letterArchive = letters.slice(1);
  const letterPages = usePagedList(letterArchive, 6, String(letterArchive.length));
  const [openCard, setOpenCard] = useState<{ title: string; body: string; reply?: string } | null>(null);

  useEffect(() => {
    if (!openCard) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setOpenCard(null);
    };
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.body.style.overflow = previousOverflow;
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [openCard]);

  const liveAnswers = [
    ...liveFaqs.filter(isPublished).map((item) => ({
      q: clean(item.q || item.question),
      a: clean(item.a || item.answer),
    })),
    ...liveQuestions.filter(isPublished).map((item) => ({
      q: clean(item.ar),
      a: clean(item.take || item.arNote),
    })),
  ].filter((item) => item.q && item.a);

  const questions = liveAnswers.filter(
    (item, index, all) =>
      all.findIndex((candidate) => clean(candidate.q) === clean(item.q)) ===
      index,
  );
  const questionPages = usePagedList(questions, 6, String(questions.length));

  const liveQuotes = liveTestimonials
    .filter(isPublished)
    .map((item) => ({ quote: clean(item.quote) }))
    .filter((item) => item.quote.length >= 35);

  /* الشهادةُ حكمٌ على الدكتور يُقدَّم للزائر دليلاً، فلا يجوز أن يكون مصنوعاً.
     حُذف البديل المخبوز (شهادتان مكتوبتان في الكود) — وحلّت محلّه أصداء من
     متونه: كلامه هو، بحرفه، منسوباً لمقاله. فإن اعتمد الدكتور شهادةً حقيقية
     من اللوحة تصدّرت مكانها فوراً. */
  const publicTestimonials = liveQuotes.filter(
    (item, index, all) =>
      all.findIndex(
        (candidate) => clean(candidate.quote) === clean(item.quote),
      ) === index,
  );
  const visibleTestimonials = rotateTestimonials(publicTestimonials).slice(
    0,
    2,
  );

  /* أصداء من المتون: تُعرض حين لا توجد شهادةٌ حقيقية معتمَدة. ولا تُخترع —
     جملُ الدكتور بحرفها من مقالاتها، تمرّ ببوّابة تحققٍ قبل العرض. */
  const { articles, books, papers } = useCmsContent();
  const archiveDialogues = useMemo(() => buildArchiveDialogues(articles, books, papers), [articles, books, papers]);
  const [echoes, setEchoes] = useState<VoiceEcho[]>([]);
  useEffect(() => {
    if (publicTestimonials.length || !articles.length) return;
    let active = true;
    loadArticleBodies()
      .then((bodies) => {
        if (active) setEchoes(pickEchoes(articles, bodies, 2));
      })
      .catch(() => {
        /* المتون زينة هنا: تعذّرها لا يكسر الصفحة */
      });
    return () => {
      active = false;
    };
  }, [articles, publicTestimonials.length]);

  const lastUpdated = Math.max(
    0,
    ...[...liveInbox, ...liveFaqs, ...liveQuestions, ...liveTestimonials].map(
      (item) => createdMillis(item.createdAt),
    ),
  );
  const updateLabel = lastUpdated
    ? new Date(lastUpdated).toLocaleDateString("ar-KW-u-nu-arab", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : "بانتظار أول تحديث حي";

  return (
    <Page className="inbox-page">
      <PageHead
        label="رسائل على الهامش"
        title="رسالةٌ تفتح نافذة."
        sub="رسائل وأسئلة تُنتقى وتُنشر تلقائياً من النظام الحي؛ لا نصوص مخبوزة ولا أرقام ثابتة."
      />
      <div className="border-b border-hair px-6 py-3 md:px-11">
        <p className="mx-auto flex max-w-shell items-center gap-2 text-[.72rem] text-soft">
          <span className="h-2 w-2 rounded-full bg-accent" aria-hidden="true" />{" "}
          تحديث تلقائي · آخر مزامنة: {updateLabel}
        </p>
      </div>

      {archiveDialogues.length > 0 && (
        <section className="border-b border-hair bg-wash/35 px-6 py-14 md:px-11 md:py-20" aria-labelledby="archive-dialogue-title">
          <div className="mx-auto max-w-shell">
            <FadeUp>
              <div className="grid gap-5 md:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)] md:items-end">
                <div>
                  <span className="text-[.72rem] font-bold text-accent">خيوط من الأرشيف</span>
                  <h2 id="archive-dialogue-title" className="mt-2 font-display text-[clamp(1.45rem,3vw,2.25rem)] font-semibold leading-[1.55] text-ink">حين تتجاور المواد، تظهر فكرة جديدة.</h2>
                </div>
                <p className="text-[.84rem] font-light leading-[1.9] text-soft">تقرأ هذه البطاقات الصلات بين المواد المنشورة، وتوضح الفرق بين فكرةٍ تُستخلص من مصدر واحد وخلاصةٍ تُبنى من أكثر من مصدر. كل مسار يعيدك إلى أصله العام القابل للفتح، ولا تُقدَّم صياغةٌ مركّبة على أنها قولٌ حرفي للدكتور.</p>
              </div>
            </FadeUp>
            <div className="archive-dialogue-rail mobile-card-rail mt-8 grid items-stretch gap-5 md:grid-cols-2">
              {archiveDialogues.map((item, index) => (
                <FadeUp key={item.id} delay={Math.min(index * .06, .2)} className="flex h-full">
                  <article className="flex h-full min-w-0 flex-col overflow-hidden rounded-[1.5rem] border border-hair bg-canvas p-6 shadow-[0_18px_55px_-48px_rgba(21,32,44,.55)] transition hover:border-accent/55">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="rounded-full bg-accent/[.08] px-3 py-1 text-[.66rem] font-bold text-accent">{item.label}</span>
                      <span className="text-[.63rem] font-semibold text-soft">{item.mode} · ليست اقتباساً حرفياً</span>
                    </div>
                    <h3 className="mt-5 font-display text-[1.12rem] font-semibold leading-[1.65] text-ink">{item.title}</h3>
                    <p className="mt-3 flex-1 text-[.86rem] font-light leading-[1.95] text-ink/78">{item.body}</p>
                    <div className="mt-6 border-t border-hair pt-4">
                      <span className="text-[.64rem] font-semibold text-soft">ارجع إلى المواد التي بنت هذا المسار</span>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {item.sources.map((source) => (
                          <Link key={`${item.id}:${source.to}`} to={source.to} className="max-w-full rounded-full border border-hair px-3 py-1.5 text-[.68rem] font-semibold text-ink transition hover:border-accent hover:text-accent">
                            <span className="text-accent">{source.kind}</span> · <span className="[overflow-wrap:anywhere]">{source.title}</span>{source.year ? ` · ${source.year}` : ''}
                          </Link>
                        ))}
                      </div>
                    </div>
                  </article>
                </FadeUp>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* الرسالة الأحدث */}
      <section className="border-b border-hair px-6 py-16 md:px-11 md:py-24">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            {/* «الرسالة الأحدث» و«ردّي» كانا يُوهمان أن قارئاً كتب وأن الدكتور أجاب،
                والنصّان معاً يولّدهما النظام من أرشيفه. النصّ باقٍ كما هو —
                والنسبة وحدها تُصحَّح، فلا يُنسب إلى غائبٍ قولٌ لم يقله. */}
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              على هامش المقال
            </span>
          </FadeUp>
          {featuredLetter ? (
            <div className="mt-8 grid gap-8 lg:grid-cols-[1.35fr_.65fr] lg:items-end">
              <FadeUp delay={0.06}>
                <blockquote className="relative overflow-hidden rounded-[2rem] border border-hair bg-wash px-7 py-9 md:px-11 md:py-12">
                  <span className="absolute right-8 top-3 font-display text-[5rem] leading-none text-accent/15">
                    ”
                  </span>
                  <p className="relative line-clamp-5 font-display text-[clamp(1.2rem,2.2vw,1.72rem)] font-light leading-[2] text-ink/92">
                    {featuredLetter.message}
                  </p>
                  <button type="button" onClick={() => setOpenCard({ title: "رسالة على الهامش", body: featuredLetter.message, reply: featuredLetter.reply })} className="relative mt-6 inline-flex min-h-10 items-center text-[.8rem] font-semibold text-accent transition-colors hover:text-accent-deep">
                    فتح الرسالة كاملة ←
                  </button>
                </blockquote>
              </FadeUp>
              {featuredLetter.reply && (
                <FadeUp delay={0.13}>
                  <div className="border-s-2 border-accent ps-6">
                    <span className="text-[.72rem] font-semibold uppercase text-accent">
                      تعقيب الدكتور
                    </span>
                    <p className="mt-3 line-clamp-4 font-display text-[1.06rem] leading-[1.95] text-ink/82">
                      {featuredLetter.reply}
                    </p>
                  </div>
                </FadeUp>
              )}
            </div>
          ) : (
            <FadeUp delay={0.06}>
              <div className="mt-8 rounded-[2rem] border border-hair bg-wash p-8 text-soft">
                لا توجد رسالة حيّة معتمدة الآن. في الأعلى يواصل «خيوط من الأرشيف» كشف صلات موثقة من المواد العامة.
              </div>
            </FadeUp>
          )}

          {letterArchive.length > 0 && (
            <div id="inbox-letters" className="mobile-card-rail mt-12 scroll-mt-28 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
              {letterPages.pageItems.map((letter, index) => (
                <FadeUp key={letter.id} delay={Math.min(index * 0.05, 0.25)}>
                  <button type="button" onClick={() => setOpenCard({ title: "رسالة على الهامش", body: letter.message, reply: letter.reply })} className="group flex h-full w-full flex-col rounded-2xl border border-hair bg-canvas p-6 text-right transition-colors hover:border-accent">
                    <p className="line-clamp-3 font-display text-[1.02rem] font-light leading-[1.9] text-ink/84">{letter.message}</p>
                    <span className="mt-5 text-[.78rem] font-semibold text-accent">فتح الرسالة ←</span>
                  </button>
                </FadeUp>
              ))}
            </div>
          )}
          <Pagination page={letterPages.page} pageCount={letterPages.pageCount} onChange={letterPages.setPage} totalItems={letterArchive.length} firstItem={letterPages.firstItem} lastItem={letterPages.lastItem} scrollTargetId="inbox-letters" label="صفحات الرسائل" className="mt-9" />
        </div>
      </section>

      {/* شهادات حقيقية معتمَدة — أو أصداء من متون الدكتور حين لا توجد */}
      <section className="border-b border-hair px-6 py-16 md:px-11 md:py-20">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              {publicTestimonials.length ? "ماذا قالوا" : "أصداء من المتون"}
            </span>
            {!publicTestimonials.length && (
              <p className="mt-2 text-[.84rem] font-light text-soft">
                جملٌ من مقالات الدكتور، بنصّها ومصدرها.
              </p>
            )}
          </FadeUp>
          {!publicTestimonials.length && echoes.length > 0 && (
            <div className="mobile-card-rail mt-8 grid gap-6 md:grid-cols-2">
              {echoes.map((echo, i) => (
                <motion.figure
                  key={echo.slug}
                  initial={reduce ? false : { opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.7, delay: i * 0.08, ease: EASE }}
                  className="relative flex h-full flex-col rounded-2xl border border-hair bg-wash p-8 md:p-9"
                >
                  <span className="absolute right-7 top-3 font-display text-[3.5rem] leading-none text-accent/20">
                    ”
                  </span>
                  <blockquote className="relative font-display text-[1.16rem] font-light leading-[1.95] text-ink/90">
                    {echo.quote}
                  </blockquote>
                  <figcaption className="mt-5 border-t border-hair pt-4 text-[.82rem] text-soft">
                    <Link
                      to={`/articles/${echo.slug}`}
                      data-hover
                      className="font-semibold text-ink transition-colors hover:text-accent"
                    >
                      {echo.title}
                    </Link>
                    {echo.iso && (
                      <span className="mt-1 block text-[.74rem] font-light text-soft/75">
                        {echo.iso.slice(0, 4)}
                      </span>
                    )}
                  </figcaption>
                </motion.figure>
              ))}
            </div>
          )}

          {!publicTestimonials.length && echoes.length === 0 && (
            <p className="mt-8 rounded-2xl border border-hair bg-wash px-6 py-5 text-[.88rem] font-light text-soft">
              يختار النظام تلقائيًا أصداءً موثقة من المقالات المنشورة، وتظهر هنا
              فور اكتمال المزامنة.
            </p>
          )}

          <div
            className={`mobile-card-rail mt-8 grid gap-6 md:grid-cols-2 ${publicTestimonials.length ? "" : "hidden"}`}
          >
            {visibleTestimonials.map((t, i) => (
              <motion.blockquote
                key={i}
                initial={reduce ? false : { opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.2 }}
                transition={{ duration: 0.7, delay: i * 0.08, ease: EASE }}
                className="relative rounded-2xl border border-hair bg-wash p-8 md:p-9"
              >
                <span className="absolute right-7 top-3 font-display text-[3.5rem] leading-none text-accent/20">
                  ”
                </span>
                <p className="relative font-display text-[1.16rem] font-light leading-[1.95] text-ink/90">
                  {t.quote}
                </p>
              </motion.blockquote>
            ))}
          </div>
        </div>
      </section>

      {/* أسئلة تصلني */}
      <section className="px-6 py-16 md:px-11 md:py-20">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              أسئلة تصلني
            </span>
          </FadeUp>
          {questions.length > 0 && (
            <div id="inbox-questions" className="mobile-card-rail mt-9 scroll-mt-28 grid gap-8 md:grid-cols-3">
              {questionPages.pageItems.map((f, i) => (
                <FadeUp key={f.q} delay={i * 0.07}>
                  <button type="button" onClick={() => setOpenCard({ title: f.q, body: f.a })} className="group w-full border-t-2 border-accent pt-5 text-right">
                    <h3 className="font-display text-[1.18rem] font-medium leading-[1.6] text-ink">{f.q}</h3>
                    <p className="mt-3.5 line-clamp-3 text-[.94rem] font-light leading-[1.9] text-ink/75">{f.a}</p>
                    <span className="mt-4 inline-block text-[.76rem] font-semibold text-accent">قراءة كاملة ←</span>
                  </button>
                </FadeUp>
              ))}
            </div>
          )}

          <Pagination page={questionPages.page} pageCount={questionPages.pageCount} onChange={questionPages.setPage} totalItems={questions.length} firstItem={questionPages.firstItem} lastItem={questionPages.lastItem} scrollTargetId="inbox-questions" label="صفحات الأسئلة" className="mt-9" />

          {questions.length === 0 && (
            <p className="mt-9 rounded-2xl border border-hair bg-wash px-6 py-5 text-[.88rem] font-light text-soft">
              لا يوجد سؤال منشور الآن؛ تُضاف الأسئلة والإجابات تلقائيًا من
              النظام الحي بعد اعتمادها.
            </p>
          )}

          <FadeUp delay={0.12}>
            <div className="mt-16">
              <Newsletter />
            </div>
          </FadeUp>
        </div>
      </section>
      {openCard && typeof document !== "undefined" ? createPortal(
        <div className="reader-modal-overlay fixed inset-0 z-[320] flex items-end justify-center bg-ink/35 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={openCard.title} onMouseDown={(event) => { if (event.target === event.currentTarget) setOpenCard(null) }}>
          <article className="max-h-[88dvh] w-full max-w-2xl overflow-y-auto rounded-t-[1.75rem] border border-hair bg-canvas p-6 shadow-2xl sm:rounded-[1.75rem] sm:p-9" tabIndex={-1}>
            <div className="flex items-start justify-between gap-5 border-b border-hair pb-5">
              <h2 className="font-display text-[1.25rem] font-semibold leading-relaxed text-ink">{openCard.title}</h2>
              <button type="button" autoFocus onClick={() => setOpenCard(null)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-hair text-soft hover:border-accent hover:text-accent" aria-label="إغلاق">×</button>
            </div>
            <p className="mt-6 whitespace-pre-line font-display text-[1.05rem] font-light leading-[2] text-ink/88">{openCard.body}</p>
            {openCard.reply && <div className="mt-7 border-r-2 border-accent pr-5"><span className="text-[.72rem] font-semibold text-accent">تعقيب الدكتور</span><p className="mt-2 whitespace-pre-line leading-[1.95] text-ink/82">{openCard.reply}</p></div>}
          </article>
        </div>,
        document.body,
      ) : null}
    </Page>
  );
}
