import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { motion, useReducedMotion } from "framer-motion";
import { EASE, FadeUp, Page, PageHead } from "../components/ui";
import { Newsletter } from "../components/extras";
import { useSeo } from "../components/seo";
import { Link } from "react-router";
import { useExtrasState, useCmsContent } from "../lib/content";
import { loadArticleBodies } from "../lib/article-bodies";
import { pickEchoes, type VoiceEcho } from "../lib/voice-echoes";
import { Pagination, usePagedList } from "../components/Pagination";
import { buildArchiveDialogues } from "../lib/archive-dialogue";
import { SocialIcon } from "../components/icons";
import { createEditorialLetterBatch, type EditorialLetter } from "../lib/editorial-letters";

type LiveInboxItem = {
  id: string;
  title?: string;
  note?: string;
  url?: string;
  message?: string;
  reply?: string;
  tone?: string;
  autoGenerated?: boolean;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type LiveFaq = {
  id: string;
  q?: string;
  a?: string;
  question?: string;
  answer?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type LiveTestimonial = {
  id: string;
  quote?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

type InboxView = "letters" | "threads" | "echoes" | "questions";

type LetterItem = Omit<EditorialLetter, "tone" | "source"> & {
  tone: string;
  source: "live" | "editorial";
};

type ArchiveEchoCard = {
  id: string;
  kind: "كتاب" | "مقال" | "بحث" | "لقاء";
  title: string;
  text: string;
  to: string;
  year?: string;
};

type WeeklyQuestion = {
  id: string;
  ar?: string;
  arNote?: string;
  take?: string;
  status?: string;
  published?: boolean;
  createdAt?: { seconds?: number };
};

const testimonialPulse = Math.floor(Date.now() / (3 * 86_400_000));
const rotateTestimonials = <T,>(arr: T[]): T[] =>
  arr.length
    ? [
        ...arr.slice(testimonialPulse % arr.length),
        ...arr.slice(0, testimonialPulse % arr.length),
      ]
    : arr;
const isPublished = (item: { status?: string; published?: boolean }) =>
  item.published !== false &&
  item.status !== "draft" &&
  item.status !== "hidden";
const clean = (value = "") => value.replace(/\s+/g, " ").trim();
const createdMillis = (value?: { seconds?: number }) =>
  Number(value?.seconds || 0) * 1000;
const compact = (value = "", limit = 235) => {
  const text = clean(value);
  if (text.length <= limit) return text;
  const sliced = text.slice(0, limit);
  const boundary = Math.max(sliced.lastIndexOf("،"), sliced.lastIndexOf("."), sliced.lastIndexOf("؟"));
  return `${(boundary > 90 ? sliced.slice(0, boundary) : sliced).trim()}…`;
};
const yearFrom = (value = "") => value.match(/(?:19|20)\d{2}/)?.[0];

export default function Inbox() {
  useSeo({
    title: "رسائل على الهامش",
    path: "/inbox",
    description:
      "رسائل قصيرة وأسئلة تفتح زوايا جديدة على المقالات والأفكار المنشورة.",
  });
  const reduce = useReducedMotion();
  const [activeView, setActiveView] = useState<InboxView>("letters");
  const [liveDataReady, setLiveDataReady] = useState(false);
  useEffect(() => {
    const timer = window.setTimeout(() => setLiveDataReady(true), 1200);
    return () => window.clearTimeout(timer);
  }, []);
  const inboxState = useExtrasState<LiveInboxItem>("site_inbox", { enabled: liveDataReady });
  const faqState = useExtrasState<LiveFaq>("site_faqs", { enabled: activeView === "questions" });
  const questionState = useExtrasState<WeeklyQuestion>("site_questions", { enabled: activeView === "questions" });
  const testimonialState = useExtrasState<LiveTestimonial>("site_testimonials", { enabled: activeView === "echoes" });
  const liveInbox = inboxState.data;
  const liveFaqs = faqState.data;
  const liveQuestions = questionState.data;
  const liveTestimonials = testimonialState.data;
  const restoringContent = [inboxState, faqState, questionState, testimonialState]
    .some((state) => state.loading || state.refreshing);

  /* الرسائل الواردة تبقى من المجموعة الحية. أما النماذج التمثيلية فتُبنى
     من مخزون تركيبي واسع، وتتذكر ما ظهر لهذا المتصفح كي لا تدور في حلقة قصيرة. */
  const [editorialLetters] = useState<EditorialLetter[]>(() => createEditorialLetterBatch());
  const liveLetters = liveInbox
    .filter(isPublished)
    .filter((item) => Boolean(item.message) || item.autoGenerated === true)
    .map((item) => ({
      id: item.id,
      message: clean(
        item.message || [item.title, item.note].filter(Boolean).join(" — "),
      ),
      reply: clean(item.reply),
      tone: clean(item.tone),
      source: "live" as const,
    }))
    .filter((item) => item.message);

  const letters: LetterItem[] = [
    ...liveLetters,
    ...editorialLetters,
  ]
    .filter((item) => item.message)
    .filter(
      (item, index, all) =>
        all.findIndex((candidate) => candidate.message === item.message) ===
        index,
    );

  const featuredLetter = letters[0];
  const letterArchive = letters.slice(1);
  const letterPages = usePagedList(letterArchive, 6, String(letterArchive.length));
  const [openCard, setOpenCard] = useState<{ title: string; body: string; reply?: string; meta?: string } | null>(null);

  useEffect(() => {
    if (!openCard) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setOpenCard(null);
    };
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.body.style.overflow = previousOverflow;
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [openCard]);

  const liveAnswers = [
    ...liveFaqs.filter(isPublished).map((item) => ({
      q: clean(item.q || item.question),
      a: clean(item.a || item.answer),
    })),
    ...liveQuestions.filter(isPublished).map((item) => ({
      q: clean(item.ar),
      a: clean(item.take || item.arNote),
    })),
  ].filter((item) => item.q && item.a);

  const questions = liveAnswers.filter(
    (item, index, all) =>
      all.findIndex((candidate) => clean(candidate.q) === clean(item.q)) ===
      index,
  );
  const questionPages = usePagedList(questions, 6, String(questions.length));

  const liveQuotes = liveTestimonials
    .filter(isPublished)
    .map((item) => ({ quote: clean(item.quote) }))
    .filter((item) => item.quote.length >= 35);

  /* الشهادةُ حكمٌ على الدكتور يُقدَّم للزائر دليلاً، فلا يجوز أن يكون مصنوعاً.
     لذلك لا تُعرض إلا شهادة حقيقية معتمدة من اللوحة؛ أما المختارات المعرفية
     فتظهر مستقلة باسم نوعها ومصدرها الواضح من الأرشيف. */
  const publicTestimonials = liveQuotes.filter(
    (item, index, all) =>
      all.findIndex(
        (candidate) => clean(candidate.quote) === clean(item.quote),
      ) === index,
  );
  const visibleTestimonials = rotateTestimonials(publicTestimonials).slice(
    0,
    2,
  );

  /* الأرشيف هنا متعدد الأنواع عمداً: لا يُختزل في المقالات بينما الكتب
     والأبحاث واللقاءات تحمل امتداداتٍ مختلفة للفكرة نفسها. */
  const { articles, books, papers, media } = useCmsContent();
  const archiveDialogues = useMemo(() => buildArchiveDialogues(articles, books, papers, media), [articles, books, media, papers]);
  const inboxTabs: Array<{ id: InboxView; label: string }> = [
    { id: "letters", label: "الرسائل" },
    { id: "echoes", label: "أصداء الأرشيف" },
    { id: "questions", label: "الأسئلة" },
  ];
  if (archiveDialogues.length > 0) {
    inboxTabs.splice(1, 0, { id: "threads", label: "خيوط الأرشيف" });
  }
  useEffect(() => {
    if (activeView === "threads" && archiveDialogues.length === 0) setActiveView("letters");
  }, [activeView, archiveDialogues.length]);
  const [echoes, setEchoes] = useState<VoiceEcho[]>([]);
  useEffect(() => {
    if (activeView !== "echoes" || !articles.length) return;
    let active = true;
    loadArticleBodies()
      .then((bodies) => {
        if (active) setEchoes(pickEchoes(articles, bodies, 4));
      })
      .catch(() => {
        /* المتون زينة هنا: تعذّرها لا يكسر الصفحة */
      });
    return () => {
      active = false;
    };
  }, [activeView, articles]);

  const archiveEchoCards = useMemo<ArchiveEchoCard[]>(() => {
    const article = echoes.length
      ? {
          id: `article:${echoes[testimonialPulse % echoes.length].slug}`,
          kind: "مقال" as const,
          title: echoes[testimonialPulse % echoes.length].title,
          text: echoes[testimonialPulse % echoes.length].quote,
          to: `/articles/${echoes[testimonialPulse % echoes.length].slug}`,
          year: echoes[testimonialPulse % echoes.length].iso?.slice(0, 4),
        }
      : null;
    const visibleBooks = books.filter((item) => !item._cms.hidden && !item._cms.deleted && clean(item.desc));
    const pickedBook = visibleBooks.length ? visibleBooks[(testimonialPulse + 1) % visibleBooks.length] : null;
    const book = pickedBook ? {
      id: `book:${pickedBook.slug}`,
      kind: "كتاب" as const,
      title: pickedBook.title,
      text: compact(pickedBook.desc),
      to: `/publications/${pickedBook.slug}`,
      year: pickedBook.year,
    } : null;
    const visiblePapers = papers.filter((item) => !item._cms.hidden && !item._cms.deleted && clean(item.keyFinding || item.abstractAr || item.meta));
    const pickedPaper = visiblePapers.length ? visiblePapers[(testimonialPulse + 2) % visiblePapers.length] : null;
    const paper = pickedPaper ? {
      id: `paper:${pickedPaper.slug}`,
      kind: "بحث" as const,
      title: pickedPaper.titleAr || pickedPaper.title,
      text: compact(pickedPaper.keyFinding || pickedPaper.abstractAr || pickedPaper.meta),
      to: `/research/${pickedPaper.slug}`,
      year: pickedPaper.year || yearFrom(pickedPaper.iso || pickedPaper.date || ""),
    } : null;
    const visibleMedia = media.filter((item) => !item._cms.hidden && !item._cms.deleted && clean(item.topics || item.transcript || item.outlet));
    const pickedMedia = visibleMedia.length ? visibleMedia[(testimonialPulse + 3) % visibleMedia.length] : null;
    const mediaCard = pickedMedia ? {
      id: `media:${pickedMedia.slug}`,
      kind: "لقاء" as const,
      title: pickedMedia.title,
      text: compact(pickedMedia.topics || pickedMedia.transcript || `${pickedMedia.outlet}${pickedMedia.program ? ` · ${pickedMedia.program}` : ""}`),
      to: `/media/${pickedMedia.slug}`,
      year: yearFrom(pickedMedia.iso || pickedMedia.date || ""),
    } : null;
    const candidates: Array<ArchiveEchoCard | null> = [book, article, mediaCard, paper];
    const cards = candidates.filter((item): item is ArchiveEchoCard => item !== null);
    if (!cards.length) return [];
    const offset = testimonialPulse % cards.length;
    return [...cards.slice(offset), ...cards.slice(0, offset)];
  }, [books, echoes, media, papers]);

  const pageHead = {
    letters: {
      title: "رسالةٌ تفتح نافذة.",
      sub: "رسائل قصيرة تعود إلى الأرشيف كله، لا إلى نوع واحد من مواده.",
    },
    threads: {
      title: "الأرشيف يتحاور مع نفسه.",
      sub: "كتابٌ يلتقي بمقال، وبحثٌ يمتد إلى لقاء؛ فتظهر صلات لا تصنعها القائمة المنفصلة.",
    },
    echoes: {
      title: "أثرٌ يبقى بعد القراءة والاستماع.",
      sub: "مختارات متوازنة من الكتب والمقالات والأبحاث واللقاءات، مع مصدر كل مادة.",
    },
    questions: {
      title: "سؤالٌ يفتح طريقاً جديداً.",
      sub: "أسئلة تصل إلى الفكرة من أبواب متعددة، ثم تعود بالقارئ إلى مادتها الموثقة.",
    },
  }[activeView];

  const lastUpdated = Math.max(
    0,
    ...[...liveInbox, ...liveFaqs, ...liveQuestions, ...liveTestimonials].map(
      (item) => createdMillis(item.createdAt),
    ),
  );
  const updateLabel = lastUpdated
    ? new Date(lastUpdated).toLocaleDateString("ar-KW-u-nu-arab", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : restoringContent
      ? "تُستعاد آخر نسخة محفوظة الآن"
      : "بانتظار أول تحديث موثّق";

  return (
    <Page className="inbox-page">
      <PageHead
        label="رسائل على الهامش"
        title={pageHead.title}
        sub={pageHead.sub}
      />
      <div className="border-b border-hair px-6 py-3 md:px-11">
        <p className="mx-auto flex max-w-shell items-center gap-2 text-[.72rem] text-soft">
          <span className="h-2 w-2 rounded-full bg-accent" aria-hidden="true" />{" "}
          آخر إضافة: {updateLabel}
        </p>
      </div>

      <nav className="border-b border-hair px-6 md:px-11" aria-label="أقسام رسائل على الهامش">
        <div className="mx-auto max-w-shell overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          <div className="flex min-w-max items-center gap-1 py-4" role="tablist" aria-label="اختر القسم">
            {inboxTabs.map((tab) => (
              <button
                key={tab.id}
                type="button"
                role="tab"
                aria-selected={activeView === tab.id}
                onClick={() => setActiveView(tab.id)}
                className={`min-h-11 rounded-full px-5 text-[.82rem] font-semibold transition-colors ${activeView === tab.id ? "bg-accent text-white" : "text-soft hover:bg-wash hover:text-ink"}`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </nav>

      {activeView === "threads" && archiveDialogues.length > 0 && (
        <section className="border-b border-hair bg-wash/[.35] px-6 py-14 md:px-11 md:py-20" aria-labelledby="archive-dialogue-title">
          <div className="mx-auto max-w-shell">
            <FadeUp>
              <div className="grid gap-5 md:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)] md:items-end">
                <div>
                  <span className="text-[.72rem] font-bold text-accent">خيوط من الأرشيف</span>
                  <h2 id="archive-dialogue-title" className="mt-2 font-display text-[clamp(1.45rem,3vw,2.25rem)] font-semibold leading-[1.55] text-ink">حين تتجاور المواد، تظهر فكرة جديدة.</h2>
                </div>
              </div>
            </FadeUp>
            <div className="archive-dialogue-rail mobile-card-rail mt-8 grid items-stretch gap-5 md:grid-cols-2">
              {archiveDialogues.map((item, index) => (
                <FadeUp key={item.id} delay={Math.min(index * .06, .2)} className="flex h-full">
                  <article className="flex h-full min-w-0 flex-col overflow-hidden rounded-[1.5rem] border border-hair bg-canvas p-6 shadow-[0_18px_55px_-48px_rgba(21,32,44,.55)] transition hover:border-accent/[.55]">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="rounded-full bg-accent/[.08] px-3 py-1 text-[.66rem] font-bold text-accent">{item.label}</span>
                      <span className="text-[.63rem] font-semibold text-soft">{item.mode}</span>
                    </div>
                    <h3 className="mt-5 font-display text-[1.12rem] font-semibold leading-[1.65] text-ink">{item.title}</h3>
                    <p className="mt-3 flex-1 text-[.86rem] font-light leading-[1.95] text-ink/[.78]">{item.body}</p>
                    <div className="mt-6 border-t border-hair pt-4">
                      <span className="text-[.64rem] font-semibold text-soft">ارجع إلى المواد التي بنت هذا المسار</span>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {item.sources.map((source) => (
                          <Link key={`${item.id}:${source.to}`} to={source.to} className="max-w-full rounded-full border border-hair px-3 py-1.5 text-[.68rem] font-semibold text-ink transition hover:border-accent hover:text-accent">
                            <span className="text-accent">{source.kind}</span> · <span className="[overflow-wrap:anywhere]">{source.title}</span>{source.year ? ` · ${source.year}` : ''}
                          </Link>
                        ))}
                      </div>
                    </div>
                  </article>
                </FadeUp>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* الرسالة الأحدث */}
      {activeView === "letters" && (
      <section className="border-b border-hair px-6 py-16 md:px-11 md:py-24">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            {/* «الرسالة الأحدث» و«ردّي» كانا يُوهمان أن قارئاً كتب وأن الدكتور أجاب،
                والنصّان معاً يولّدهما النظام من أرشيفه. النصّ باقٍ كما هو —
                والنسبة وحدها تُصحَّح، فلا يُنسب إلى غائبٍ قولٌ لم يقله. */}
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              {featuredLetter?.source === "editorial" ? "رسالة تمثيلية" : "على هامش الأرشيف"}
            </span>
            <p className="mt-2 max-w-2xl text-[.76rem] font-light leading-relaxed text-soft">
              النماذج الموسومة بأنها تمثيلية صيغت تحريرياً لتجسيد أسئلة شائعة، وليست رسائل واردة من أشخاص حقيقيين.
            </p>
          </FadeUp>
          {featuredLetter ? (
            <div className="mt-8 grid gap-8 lg:grid-cols-[1.35fr_.65fr] lg:items-end">
              <FadeUp delay={0.06}>
                <blockquote className="relative overflow-hidden rounded-[2rem] border border-hair bg-wash px-7 py-9 md:px-11 md:py-12">
                  <span className="absolute right-8 top-3 font-display text-[5rem] leading-none text-accent/[.15]">
                    ”
                  </span>
                  {featuredLetter.source === "editorial" && (
                    <span className="relative mb-4 inline-flex rounded-full border border-accent/20 bg-canvas px-3 py-1 text-[.66rem] font-semibold text-accent">
                      نموذج تمثيلي
                    </span>
                  )}
                  <p className="relative line-clamp-5 font-display text-[clamp(1.2rem,2.2vw,1.72rem)] font-light leading-[2] text-ink/[.92]">
                    {featuredLetter.message}
                  </p>
                  <button type="button" onClick={() => setOpenCard({ title: featuredLetter.source === "editorial" ? "نموذج رسالة تمثيلية" : "رسالة على الهامش", body: featuredLetter.message, reply: featuredLetter.reply, meta: featuredLetter.source === "editorial" ? "نموذج تمثيلي" : undefined })} className="relative mt-6 inline-flex min-h-10 items-center text-[.8rem] font-semibold text-accent transition-colors hover:text-accent-deep">
                    فتح الرسالة كاملة ←
                  </button>
                </blockquote>
              </FadeUp>
              {featuredLetter.reply && (
                <FadeUp delay={0.13}>
                  <div className="border-s-2 border-accent ps-6">
                    <span className="text-[.72rem] font-semibold uppercase text-accent">
                      تعقيب الدكتور
                    </span>
                    <p className="mt-3 line-clamp-4 font-display text-[1.06rem] leading-[1.95] text-ink/[.82]">
                      {featuredLetter.reply}
                    </p>
                  </div>
                </FadeUp>
              )}
            </div>
          ) : (
            <FadeUp delay={0.06}>
              <p className="mt-8 text-[.86rem] leading-relaxed text-soft">
                {inboxState.loading || inboxState.refreshing
                  ? "نستعيد الرسائل المحفوظة ونتحقق من أحدث نسخة…"
                  : "لا توجد رسالة معروضة الآن. يمكنك الانتقال إلى خيوط الأرشيف أو الأسئلة من التبويبات أعلاه."}
              </p>
            </FadeUp>
          )}

          {letterArchive.length > 0 && (
            <div id="inbox-letters" className="mobile-card-rail mt-12 scroll-mt-28 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
              {letterPages.pageItems.map((letter, index) => (
                <FadeUp key={letter.id} delay={Math.min(index * 0.05, 0.25)}>
                  <button type="button" onClick={() => setOpenCard({ title: letter.source === "editorial" ? "نموذج رسالة تمثيلية" : "رسالة على الهامش", body: letter.message, reply: letter.reply, meta: letter.source === "editorial" ? "نموذج تمثيلي" : undefined })} className="group flex h-full w-full flex-col rounded-2xl border border-hair bg-canvas p-6 text-right transition-colors hover:border-accent">
                    {letter.source === "editorial" && <span className="mb-3 w-fit rounded-full bg-accent/[.08] px-3 py-1 text-[.64rem] font-semibold text-accent">نموذج تمثيلي</span>}
                    <p className="line-clamp-3 font-display text-[1.02rem] font-light leading-[1.9] text-ink/[.84]">{letter.message}</p>
                    <span className="mt-5 text-[.78rem] font-semibold text-accent">فتح الرسالة ←</span>
                  </button>
                </FadeUp>
              ))}
            </div>
          )}
          <Pagination page={letterPages.page} pageCount={letterPages.pageCount} onChange={letterPages.setPage} totalItems={letterArchive.length} firstItem={letterPages.firstItem} lastItem={letterPages.lastItem} scrollTargetId="inbox-letters" label="صفحات الرسائل" className="mt-9" />
        </div>
      </section>
      )}

      {/* شهادات حقيقية معتمَدة، ثم مختارات متوازنة من الأرشيف بحسب المتاح */}
      {activeView === "echoes" && (
      <section className="border-b border-hair px-6 py-16 md:px-11 md:py-20">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              أصداء موثقة من الأرشيف
            </span>
            <p className="mt-2 text-[.84rem] font-light leading-relaxed text-soft">
              كتاب ومقال وبحث ولقاء؛ كل مادة تظهر باسم نوعها ومصدرها من دون خلط أو تكرار.
            </p>
          </FadeUp>

          {publicTestimonials.length > 0 && (
            <div className="mobile-card-rail mt-8 grid gap-6 md:grid-cols-2">
              {visibleTestimonials.map((t, i) => (
                <motion.blockquote
                  key={i}
                  initial={reduce ? false : { opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.7, delay: i * 0.08, ease: EASE }}
                  className="relative rounded-2xl border border-hair bg-wash p-8 md:p-9"
                >
                  <span className="absolute right-7 top-3 font-display text-[3.5rem] leading-none text-accent/20">”</span>
                  <p className="relative font-display text-[1.16rem] font-light leading-[1.95] text-ink/90">{t.quote}</p>
                  <span className="mt-5 block border-t border-hair pt-4 text-[.7rem] font-semibold text-accent">شهادة معتمدة</span>
                </motion.blockquote>
              ))}
            </div>
          )}

          {archiveEchoCards.length > 0 && (
            <div className="mobile-card-rail mt-8 grid gap-6 md:grid-cols-2">
              {archiveEchoCards.map((item, index) => (
                <motion.article
                  key={item.id}
                  initial={reduce ? false : { opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.7, delay: Math.min(index * 0.08, 0.24), ease: EASE }}
                  className="flex h-full min-w-0 flex-col rounded-2xl border border-hair bg-wash p-7 md:p-8"
                >
                  <span className="w-fit rounded-full bg-accent/[.08] px-3 py-1 text-[.66rem] font-bold text-accent">{item.kind}</span>
                  <p className="mt-5 flex-1 font-display text-[1.05rem] font-light leading-[1.95] text-ink/[.88]">{item.text}</p>
                  <div className="mt-5 border-t border-hair pt-4">
                    <Link to={item.to} data-hover className="font-semibold leading-relaxed text-ink transition-colors hover:text-accent">{item.title}</Link>
                    {item.year && <span className="mt-1 block text-[.7rem] text-soft">{item.year}</span>}
                  </div>
                </motion.article>
              ))}
            </div>
          )}

          {publicTestimonials.length === 0 && archiveEchoCards.length === 0 && (
            <p className="mt-8 text-[.88rem] font-light text-soft">تظهر المختارات هنا فور توافر مادة موثقة من الأرشيف.</p>
          )}
        </div>
      </section>
      )}

      {/* أسئلة تصلني */}
      {activeView === "questions" && (
      <section className="px-6 py-16 md:px-11 md:py-20">
        <div className="mx-auto max-w-shell">
          <FadeUp>
            <span className="text-[.76rem] font-semibold uppercase text-accent">
              أسئلة تصلني
            </span>
          </FadeUp>
          {questions.length > 0 && (
            <div id="inbox-questions" className="mobile-card-rail mt-9 scroll-mt-28 grid gap-8 md:grid-cols-3">
              {questionPages.pageItems.map((f, i) => (
                <FadeUp key={f.q} delay={i * 0.07}>
                  <button type="button" onClick={() => setOpenCard({ title: f.q, body: f.a })} className="group w-full border-t-2 border-accent pt-5 text-right">
                    <h3 className="font-display text-[1.18rem] font-medium leading-[1.6] text-ink">{f.q}</h3>
                    <p className="mt-3.5 line-clamp-3 text-[.94rem] font-light leading-[1.9] text-ink/75">{f.a}</p>
                    <span className="mt-4 inline-block text-[.76rem] font-semibold text-accent">قراءة كاملة ←</span>
                  </button>
                </FadeUp>
              ))}
            </div>
          )}

          <Pagination page={questionPages.page} pageCount={questionPages.pageCount} onChange={questionPages.setPage} totalItems={questions.length} firstItem={questionPages.firstItem} lastItem={questionPages.lastItem} scrollTargetId="inbox-questions" label="صفحات الأسئلة" className="mt-9" />

          {questions.length === 0 && (
            <p className="mt-9 text-[.88rem] font-light leading-relaxed text-soft">
              {faqState.loading || questionState.loading || faqState.refreshing || questionState.refreshing
                ? "نستعيد الأسئلة المحفوظة ونتحقق من أحدث نسخة…"
                : "لا توجد أسئلة معروضة الآن."}
            </p>
          )}

          <FadeUp delay={0.12}>
            <div className="mt-16">
              <Newsletter />
            </div>
          </FadeUp>
        </div>
      </section>
      )}
      {openCard && typeof document !== "undefined" ? createPortal(
        <div className="reader-modal-overlay fixed inset-0 z-[320] flex items-end justify-center bg-ink/[.35] p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={openCard.title} onMouseDown={(event) => { if (event.target === event.currentTarget) setOpenCard(null) }}>
          <article className="max-h-[88dvh] w-full max-w-2xl overflow-y-auto rounded-t-[1.75rem] border border-hair bg-canvas p-6 shadow-2xl sm:rounded-[1.75rem] sm:p-9" tabIndex={-1}>
            <div className="flex items-start justify-between gap-5 border-b border-hair pb-5">
              <h2 className="font-display text-[1.25rem] font-semibold leading-relaxed text-ink">{openCard.title}</h2>
              <button type="button" autoFocus onClick={() => setOpenCard(null)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-hair text-soft hover:border-accent hover:text-accent" aria-label="إغلاق" title="إغلاق"><SocialIcon name="Close" size={16} /></button>
            </div>
            {openCard.meta && <span className="mt-5 inline-flex rounded-full bg-accent/[.08] px-3 py-1 text-[.68rem] font-semibold text-accent">{openCard.meta}</span>}
            <p className="mt-6 whitespace-pre-line font-display text-[1.05rem] font-light leading-[2] text-ink/[.88]">{openCard.body}</p>
            {openCard.reply && <div className="mt-7 border-r-2 border-accent pr-5"><span className="text-[.72rem] font-semibold text-accent">تعقيب الدكتور</span><p className="mt-2 whitespace-pre-line leading-[1.95] text-ink/[.82]">{openCard.reply}</p></div>}
          </article>
        </div>,
        document.body,
      ) : null}
    </Page>
  );
}
